services:
  postgres:
    image: postgres:17-alpine
    container_name: styling-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: styling_db
      POSTGRES_USER: styling_user
      POSTGRES_PASSWORD: styling_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: